Import('config')

SRCS = []

if 'MACH' in dir(config):
	if config.MACH == "lpc11xx" or config.MACH == "lpc13xx":
		SRCS.append('lpc13xx_gpio.c')
	if config.MACH == "lpc21xx":
		SRCS.append('lpc21xx_gpio.c')
	if config.MACH == "stm32":
		SRCS.append('stm32_gpio.c')
else:
	SRCS.append('stub_gpio.c')

obj = [ Object(i)  for i in SRCS ]

Return('obj')
