Import('env', 'config')

cfl = '-ffunction-sections -fno-builtin'
ldf = '-Xlinker --gc-sections -Xlinker -M -Xlinker -Map='+config.NAME+'.map'

env.Append(CFLAGS = cfl.split())
env.Append(LINKFLAGS = ldf.split())

SRCS = 'sched.c init.c'

obj = [ Object(i)  for i in Split(SRCS) ]

Return('obj')
