SRCS = 'circ_buf.c '
SRCS += 'printf.c '
SRCS += 'string_extra.c '

obj = [ Object(i)  for i in Split(SRCS) ]

nowarn = DefaultEnvironment().Clone()

# mallocr spews some shit
if '-Wall' in nowarn['CFLAGS']:
	nowarn['CFLAGS'].remove('-Wall')
#obj.append(nowarn.Object('mallocr.c'))

Return('obj')
