SRCS = [
    'bip_buf.c',
    'circ_buf.c',
    'helpers.c',
    'printf.c',
    'printf_test.c',
    #'string_extra.c',
    'string.c',
    ]

obj = [ Object(i)  for i in SRCS ]

nowarn = DefaultEnvironment().Clone()

# mallocr spews some shit
if '-Wall' in nowarn['CFLAGS']:
	nowarn['CFLAGS'].remove('-Wall')
#obj.append(nowarn.Object('mallocr.c'))

Return('obj')
