SUBDIRS = [
    'gpio',
    'serial',
    'spi',
    'i2c',
    '1w',
    'net',
    'pseudo',
    'misc',
    'watchdog',
    ]

obj = SConscript([ i+'/SConscript'  for i in SUBDIRS ])

Return('obj')
