Import('config')

SRCS = ['i2c.c']

if 'MACH' in dir(config):
	if config.MACH == 'lpc21xx' or config.MACH == 'lpc13xx':
		SRCS.append('lpc_i2c.c')

#SRCS += ['spi_tmp124.c']

obj = [ Object(i)  for i in SRCS ]

Return('obj')
